version: '3'

services:
  mediator:
    build: ..
    image: aries-framework-javascript
    container_name: mediator
    command: ./scripts/run-mediator.sh mediator
    platform: linux/amd64
    networks:
      - hyperledger
    ports:
      - 3001:3001

networks:
  hyperledger:
