version: '3'

# This file extends docker-compose-mediators.yml

services:
  alice-mediator:
    environment:
      NGROK_NAME: alice-ngrok
    entrypoint: ./scripts/ngrok-wait.sh
    depends_on: [alice-ngrok]

  alice-ngrok:
    image: wernight/ngrok
    command: ngrok http -bind-tls=true --log stdout alice-mediator:3001
    networks:
      - hyperledger

  bob-mediator:
    environment:
      NGROK_NAME: bob-ngrok
    entrypoint: ./scripts/ngrok-wait.sh
    depends_on: [bob-ngrok]

  bob-ngrok:
    image: wernight/ngrok
    command: ngrok http -bind-tls=true --log stdout bob-mediator:3002
    networks:
      - hyperledger

networks:
  hyperledger:
